# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprofile',
            name='address',
            field=models.CharField(blank=True, default=b'', max_length=25, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='passport_number',
            field=models.CharField(blank=True, default=b'', max_length=15, verbose_name='Passport number'),
        ),
        migrations.AddField(
            model_name='stprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
